更新 airCHESHI

diff --git a/3_project/0_air/airCHESHI b/3_project/0_air/airCHESHI
--- a/3_project/0_air/airCHESHI
+++ b/3_project/0_air/airCHESHI
@@ -184,7 +184,7 @@ EOF
 
     sudo rm -rf ~/.tracks
     cd $HOME/tracks
-    if [ ! -f "go.mod" ]; then
+    if [ ! -f "go.mod" ];then
         echo "go.mod 文件不存在，请检查 tracks 仓库是否正确克隆。"
         exit 1
     fi
@@ -304,9 +304,13 @@ function create_tx_script() {
 
 while true; do
   echo "Sending transaction from node to ${addr}" >> spam.log
-  $HOME/wasm-station/build/wasmstationd tx bank send node ${addr} 1stake --from node --chain-id station-1 --keyring-backend test -y >> spam.log 2>&1
-  if [ $? -ne 0 ]; then
-    echo "发送交易失败，正在重试..." >> spam.log
+  output=$($HOME/wasm-station/build/wasmstationd tx bank send node ${addr} 1stake --from node --chain-id station-1 --keyring-backend test -y 2>&1)
+  if [[ $? -ne 0 ]];then
+    if echo "$output" | grep -q "account sequence mismatch";then
+      echo "账户序列号不匹配错误，正在重试..." >> spam.log
+    else
+      echo "发送交易失败，正在重试..." >> spam.log
+    fi
   fi
   sleep ${delay_time}  # 添加 sleep 以避免系统或网络过载
 done
@@ -377,19 +381,19 @@ function monitor_stationd_logs() {
     ERROR_LOG_FILE="$HOME/stationd_error.log"
 
     # 调试信息：确保 journalctl 命令执行成功
-    if ! journalctl -u stationd -f -o cat > /dev/null 2>&1; then
+    if ! journalctl -u stationd -f -o cat > /dev/null 2>&1;then
         echo "journalctl 命令执行失败，请检查 journalctl 是否正确安装和配置。" | tee -a "$ERROR_LOG_FILE"
         return
     fi
 
-    journalctl -u stationd -f -o cat | while read -r line; do
+    journalctl -u stationd -f -o cat | while read -r line;do
         echo "$line" >> "$LOG_FILE"
         current_time=$(date +%s)
 
-        if echo "$line" | grep -q "$ERROR_STRING_1"; then
+        if echo "$line" | grep -q "$ERROR_STRING_1";then
             echo "检测到错误字符串 $ERROR_STRING_1" | tee -a "$ERROR_LOG_FILE"
             block_count=$((block_count + 1))
-            if [ "$block_count" -ge 25 ] && [ $((current_time - last_restart_time)) -gt $restart_interval ]; then
+            if [ "$block_count" -ge 25 ] && [ $((current_time - last_restart_time)) -gt $restart_interval ];then
                 echo "检测到连续25条 $ERROR_STRING_1 日志，重启 stationd 服务..." | tee -a "$ERROR_LOG_FILE"
                 sudo systemctl restart stationd
                 echo "$(date): 重启 stationd 服务，因为检测到连续25条 $ERROR_STRING_1 日志。" | tee -a "$LOG_FILE"
@@ -400,9 +404,9 @@ function monitor_stationd_logs() {
             block_count=0
         fi
 
-        if echo "$line" | grep -q "$ERROR_STRING_2"; then
+        if echo "$line" | grep -q "$ERROR_STRING_2";then
             echo "检测到错误字符串 $ERROR_STRING_2" | tee -a "$ERROR_LOG_FILE"
-            if [ $((current_time - last_rollback_time)) -gt $restart_interval ]; then
+            if [ $((current_time - last_rollback_time)) -gt $restart_interval ];then
                 echo "错误间隔超过 $restart_interval 秒，停止 stationd 服务并回滚..." | tee -a "$ERROR_LOG_FILE"
                 sudo systemctl stop stationd
                 cd $HOME/tracks
@@ -417,9 +421,9 @@ function monitor_stationd_logs() {
             fi
         fi
 
-        if echo "$line" | grep -q "$ERROR_STRING_3"; then
+        if echo "$line" | grep -q "$ERROR_STRING_3";then
             echo "检测到错误字符串 $ERROR_STRING_3" | tee -a "$ERROR_LOG_FILE"
-            if [ $((current_time - last_rollback_time)) -gt $restart_interval ]; then
+            if [ $((current_time - last_rollback_time)) -gt $restart_interval ];then
                 echo "错误间隔超过 $restart_interval 秒，停止 stationd 服务并回滚..." | tee -a "$ERROR_LOG_FILE"
                 sudo systemctl stop stationd
                 cd $HOME/tracks
@@ -434,13 +438,13 @@ function monitor_stationd_logs() {
             fi
         fi
 
-        if echo "$line" | grep -q "$ERROR_STRING_4"; then
+        if echo "$line" | grep -q "$ERROR_STRING_4";then
             echo "检测到错误关键词 $ERROR_STRING_4 ，重新启动 stationd 服务..." | tee -a "$ERROR_LOG_FILE"
             sudo systemctl restart stationd
             echo "$(date): 重启 stationd 服务，因为检测到 $ERROR_STRING_4 错误。" | tee "$LOG_FILE"
         fi
 
-        if echo "$line" | grep -q "$ERROR_STRING_5"; then
+        if echo "$line" | grep -q "$ERROR_STRING_5";then
             echo "检测到错误字符串 $ERROR_STRING_5" | tee -a "$ERROR_LOG_FILE"
             sudo systemctl restart stationd
             echo "$(date): 重启 stationd 服务，因为检测到 $ERROR_STRING_5 错误。" | tee "$LOG_FILE"
